# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map-reduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map-reduce.proto\x12\x06\x64river\"\x13\n\x03req\x12\x0c\n\x04text\x18\x01 \x01(\t\"Y\n\x07\x44\x65tails\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x10\n\x08workerId\x18\x02 \x01(\x05\x12\x11\n\treduceNum\x18\x03 \x01(\x05\x12\r\n\x05\x66iles\x18\x04 \x03(\t\x12\x0c\n\x04path\x18\x05 \x01(\t2\x8c\x01\n\x06\x44river\x12-\n\x0brequestTask\x12\x0b.driver.req\x1a\x0f.driver.Details\"\x00\x12\'\n\tmapResult\x12\x0b.driver.req\x1a\x0b.driver.req\"\x00\x12*\n\x0creduceResult\x12\x0b.driver.req\x1a\x0b.driver.req\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQ._serialized_start=28
  _REQ._serialized_end=47
  _DETAILS._serialized_start=49
  _DETAILS._serialized_end=138
  _DRIVER._serialized_start=141
  _DRIVER._serialized_end=281
# @@protoc_insertion_point(module_scope)
